### ISSUE TITLE
localdev fails with `jekyll 3.9.0 | Error:  no implicit conversion of Hash into Integer`

### ISSUE THREAD

**Issue by burabure** [excellalabs/blog-in-a-box#79]
fresh install

```
d6dc5ddf4e4d:/workspaces/burabure.com/docs# localdev
Configuration file: /workspaces/burabure.com/docs/_config.yml
            Source: /workspaces/burabure.com/docs
       Destination: /workspaces/burabure.com/docs/_site
 Incremental build: enabled
      Generating... 
      Remote Theme: Using theme mmistakes/minimal-mistakes
       Jekyll Feed: Generating feed for posts
   GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
                    done in 5.111 seconds.
jekyll 3.9.0 | Error:  no implicit conversion of Hash into Integer
/usr/gem/gems/pathutil-0.16.2/lib/pathutil.rb:502:in `read': no implicit conversion of Hash into Integer (TypeError)
        from /usr/gem/gems/pathutil-0.16.2/lib/pathutil.rb:502:in `read'
        from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/utils/platforms.rb:75:in `proc_version'
        from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/utils/platforms.rb:40:in `bash_on_windows?'
        from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/commands/build.rb:77:in `watch'
        from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/commands/build.rb:43:in `process'
        from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `block in start'
        from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `each'
        from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `start'
        from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
        from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        from /usr/gem/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        from /usr/gem/gems/jekyll-3.9.0/exe/jekyll:15:in `<top (required)>'
        from /usr/gem/bin/jekyll:25:in `load'
        from /usr/gem/bin/jekyll:25:in `<top (required)>'
        from /usr/gem/gems/bundler-2.2.24/lib/bundler/cli/exec.rb:63:in `load'
        from /usr/gem/gems/bundler-2.2.24/lib/bundler/cli/exec.rb:63:in `kernel_load'
        from /usr/gem/gems/bundler-2.2.24/lib/bundler/cli/exec.rb:28:in `run'
        from /usr/gem/gems/bundler-2.2.24/lib/bundler/cli.rb:475:in `exec'
        from /usr/gem/gems/bundler-2.2.24/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /usr/gem/gems/bundler-2.2.24/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/gem/gems/bundler-2.2.24/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /usr/gem/gems/bundler-2.2.24/lib/bundler/cli.rb:31:in `dispatch'
        from /usr/gem/gems/bundler-2.2.24/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /usr/gem/gems/bundler-2.2.24/lib/bundler/cli.rb:25:in `start'
        from /usr/gem/gems/bundler-2.2.24/exe/bundle:49:in `block in <top (required)>'
        from /usr/gem/gems/bundler-2.2.24/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
        from /usr/gem/gems/bundler-2.2.24/exe/bundle:37:in `<top (required)>'
        from /usr/local/bin/bundle:25:in `load'
        from /usr/local/bin/bundle:25:in `<main>'
        ````

**Comment by SeanKilleen** [comment]
Thanks for reporting this! I believe the issue is with some container changes I made thinking it'd be better compatible with GitHub pages. The container has an incompatible version of ruby and Jekyll. I'll fix this ASAP.

**Comment by SeanKilleen** [comment]
A few more notes -- this is an issue, as far as I can tell, because the Jekyll Docker container and its associated labels are not the friendliest for our purposes. We can build our container from `jekyll/jekyll`, which is jekyll 4 and incompatible with jekyll 3.9. Or we can use `jekyll/jekyll:pages` which could work for pages but has some incorrect dependencies, or we could use `jekyll/jekyll:3` which is 3 years old.

What we need is to be able to create our own container that has:

* The version of Ruby compatible with GitHub pages
* The version of Jekyll compatible with that version of Ruby and GitHub pages
* The version of node that will work well with our tools.

Up to this point, I'd been relying on someone else's container and dealing with the trade-offs.

But my hope in the PR I just started (#80), is that it will resolve this issue and allow me to peg the correct versions for the correct release of github pages.
